export const actionTypes = {
  productsActions: {
    FETCH_PRODUCTS_STARTED: "FETCH_PRODUCTS_STARTED",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_TO_SELECTED_PRODUCTS: "ADD_TO_SELECTED_PRODUCTS",
    REMOVE_FROM_SELECTED_PRODUCTS: "REMOVE_FROM_SELECTED_PRODUCTS"
  }
};
